# Generated by Django 4.0.4 on 2022-04-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('alunos', '0002_aluno_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco'),
        ),
    ]
