# Generated by Django 4.0.4 on 2022-06-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('escola', '0001_initial'),
        ('alunos', '0003_alter_aluno_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escola.escola'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='horario_entrada',
            field=models.TimeField(null=True, verbose_name='Horário de entrada'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='horario_saida',
            field=models.TimeField(null=True, verbose_name='Horário de entrada'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endereco.endereco'),
        ),
    ]
