# Generated by Django 4.0.4 on 2022-06-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_aluno_escola_aluno_horario_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('AT', 'ATIVO'), ('AR', 'AGUARDANDO ROTA'), ('IN', 'INATIVO')], default='IN', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='horario_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de entrada'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de entrada'),
        ),
    ]
