# Generated by Django 4.0.4 on 2022-06-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
        ('endereco', '0001_initial'),
        ('alunos', '0005_aluno_status_alter_aluno_horario_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endereco.endereco'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escola.escola'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('AT', 'ATIVO'), ('AR', 'AGUARDANDO ROTA OFICIAL'), ('AR', 'AGUARDANDO ROTA TESTE'), ('IN', 'INATIVO')], default='IN', max_length=50, verbose_name='Status'),
        ),
    ]
