# Generated by Django 4.0.4 on 2022-04-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Número')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
        ),
    ]
