# Generated by Django 4.0.4 on 2022-04-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0002_alter_responsavel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='status',
            field=models.CharField(choices=[('AI', 'ATENDIMENTO INICIADO'), ('DM', 'DEMONSTROU INTERESSE'), ('DM', 'NÃO DEMONSTROU INTERESSE'), ('EN', 'EM NEGOCIAÇÃO'), ('AR', 'ASSINATURA REALIZADA')], default='AI', max_length=2, verbose_name='Status'),
        ),
    ]
