# Generated by Django 4.0.4 on 2022-04-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel', '0003_responsavel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='comments',
            field=models.TextField(null=True, verbose_name='Comentários'),
        ),
    ]
