# Generated by Django 4.0.4 on 2022-06-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('responsavel', '0004_responsavel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='contrato',
            field=models.ManyToManyField(to='contratos.contrato'),
        ),
    ]
