# Generated by Django 4.0.4 on 2022-06-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendente',
            options={'verbose_name_plural': 'Atendentes'},
        ),
    ]
