# Generated by Django 4.0.4 on 2022-04-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da escola')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
        ),
    ]
