# Generated by Django 4.0.4 on 2022-06-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaviagem',
            options={'verbose_name_plural': 'Agenda de viagens'},
        ),
    ]
