# Generated by Django 4.0.4 on 2022-06-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='file',
            field=models.FileField(upload_to='contratos', verbose_name='Contrato (PDF)'),
        ),
    ]
